name: agrisheild
description: AgriShield - Intelligent crop disease detection and treatment recommendation system.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core Logic
  tflite_flutter: ^0.12.1 # Updated to support newer TFLite ops (FullyConnected v12)
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Media & Image Processing
  image_picker: ^1.0.4
  image: ^4.1.3 # For resizing/preprocessing

  # Background & Notifications
  workmanager: ^0.9.0 # Updated to fix Android embedding issues
  flutter_local_notifications: ^18.0.0 # Updated to fix BigPictureStyle error
  
  # Networking
  http: ^1.6.0
  connectivity_plus: ^5.0.0 # To check internet connection
  
  # Audio
  flutter_tts: ^3.8.3

  # UI Components
  percent_indicator: ^4.2.3

  # State Management (Optional but good)
  provider: ^6.0.5

  # Firebase Authentication
  firebase_core: ^2.24.0
  firebase_auth: ^4.14.0

  # Local Storage
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/models/crop_slm.tflite
    - assets/images/app_icon.png
    - assets/models/labelmap.txt
    - assets/i18n/
