name: anaj_ai_mobile
description: A new Flutter project for Anaj.ai.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1

  # Core Logic
  tflite_flutter: ^0.12.1 # Updated to support newer TFLite ops (FullyConnected v12)
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Media & Image Processing
  image_picker: ^1.0.4
  image: ^4.1.3 # For resizing/preprocessing

  # Background & Notifications
  workmanager: ^0.9.0 # Updated to fix Android embedding issues
  flutter_local_notifications: ^18.0.0 # Updated to fix BigPictureStyle error
  
  # Networking
  http: ^1.6.0
  connectivity_plus: ^5.0.0 # To check internet connection
  
  # Audio
  flutter_tts: ^3.8.3

  # UI Components
  percent_indicator: ^4.2.3

  # State Management (Optional but good)
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/crop_slm.tflite
    - assets/models/labelmap.txt
    - assets/i18n/
