name: anaj_ai_mobile
description: A new Flutter project for Anaj.ai.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core Logic
  tflite_flutter: ^0.10.1
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Background & Notifications
  workmanager: ^0.5.1
  flutter_local_notifications: ^16.0.0
  
  # Networking
  http: ^1.1.0
  connectivity_plus: ^5.0.0 # To check internet connection
  
  # Audio
  flutter_tts: ^3.8.3

  # UI Components
  percent_indicator: ^4.2.3

  # State Management (Optional but good)
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/i18n/
